export type Resource={slug:string;grade:string;subject:string;topic:string;title:string;description:string;formats:string[];minutes:number;objectives:string[];questions:{prompt:string;answer:string}[]};
export const resources:Resource[]=[
{slug:"multiplication-facts-1-to-10",grade:"3",subject:"Math",topic:"Multiplication",title:"Multiplication Facts 1–10",description:"Build fluency with multiplication facts using a clean, classroom-ready practice sheet.",formats:["PDF","DOCX","Interactive"],minutes:15,objectives:["Recall multiplication facts through 10 × 10","Build speed and accuracy"],questions:[{prompt:"6 × 7 =",answer:"42"},{prompt:"9 × 4 =",answer:"36"},{prompt:"8 × 8 =",answer:"64"}]},
{slug:"main-idea-practice",grade:"5",subject:"English & Reading",topic:"Reading comprehension",title:"Main Idea Practice",description:"Short reading passages and prompts for identifying main ideas and supporting details.",formats:["PDF","DOCX"],minutes:20,objectives:["Identify a passage's main idea","Use supporting details as evidence"],questions:[{prompt:"What is the main idea of the passage?",answer:"Answers depend on the passage and supporting evidence."}]},
{slug:"cell-structure-review",grade:"7",subject:"Science",topic:"Life science",title:"Cell Structure Review",description:"Review major cell structures and connect each organelle with its function.",formats:["PDF","DOCX","Interactive"],minutes:25,objectives:["Identify major cell structures","Explain basic organelle functions"],questions:[{prompt:"Which organelle contains most of a eukaryotic cell's DNA?",answer:"The nucleus."}]},
{slug:"linear-equations-one-step",grade:"8",subject:"Math",topic:"Algebra",title:"One-Step Linear Equations",description:"Practice solving one-step equations with clear, focused problems.",formats:["PDF","DOCX","Interactive"],minutes:20,objectives:["Solve one-step equations","Check solutions by substitution"],questions:[{prompt:"x + 7 = 19",answer:"x = 12"}]},
{slug:"constitutional-principles",grade:"11",subject:"Social Studies",topic:"Civics",title:"Constitutional Principles",description:"A neutral introduction to foundational constitutional concepts and vocabulary.",formats:["PDF","DOCX"],minutes:30,objectives:["Define foundational constitutional principles","Connect principles to constitutional structures"],questions:[{prompt:"What does separation of powers describe?",answer:"The division of government authority among separate branches."}]}
];
export const grades=["K","1","2","3","4","5","6","7","8","9","10","11","12"];
export const subjects=["Math","English & Reading","Science","Social Studies","World Languages","Computer Science","Art & Music","Health"];
export const getResource=(slug:string)=>resources.find(r=>r.slug===slug);